export const DATA_TASK_UPDATE = 'DATA_TASK_UPDATE';
export const DATA_TASK_ADD = 'DATA_TASK_ADD';
export const DATA_TASK_DELETE = 'DATA_TASK_DELETE';
export const DATA_TASK_EDIT = 'DATA_TASK_EDIT';

export const FORM_STATE_ADD = 'FORM_STATE_ADD';
export const FORM_STATE_EDIT = 'FORM_STATE_EDIT';
